language: generic

sudo: required
services:
  - docker

before install:
  - docker build -t bentonwong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bentonwong/react-test npm test

after success:
  - docker build -t bentonwong/multi-client ./client
  - docker build -t bentonwong/multi-nginx ./nginx
  - docker build -t bentonwong/multi-server ./server
  - docker build -t bentonwong/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bentonwong/multi-client
  - docker push bentonwong/multi-nginx
  - docker push bentonwong/multi-server
  - docker push bentonwong/multi-worker
